name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag name (default vulkan version)'
        default: ''
        type: string

jobs:
  build:
    uses: mpvkit/BuildShared/.github/workflows/build.yml@main
    secrets: inherit
    with:
      version: '${{ github.event.inputs.version }}'
      library: 'vulkan'
