name: Check new version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # every month first day

jobs:
  check_version:
    permissions:
      contents: write
      pull-requests: write
    uses: mpvkit/BuildShared/.github/workflows/check_version.yml@9c51172cc0fe59112866090f4f307f73c4bc27e3
    secrets: inherit
    with:
      repository: 'KhronosGroup/MoltenVK'
      library: 'vulkan'
