name: CI Test

on:
  push:
    branches:
      - ci
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag name (default vulkan version)'
        default: ''

jobs:
  build:
    permissions:
      contents: write
    uses: mpvkit/BuildShared/.github/workflows/build.yml@9c51172cc0fe59112866090f4f307f73c4bc27e3
    secrets: inherit
    with:
      version: '${{ github.event.inputs.version }}'
      library: 'vulkan'
      try_run: true
